In [1]:
import sqlite3
import pandas as pd
faili_nimi = 'run_01_gpt-4.db'

In [2]:
conn = sqlite3.connect(faili_nimi)

df = pd.read_sql_query("SELECT * FROM model_annotations;", conn)
conn.close()
df

,input,model,semantic_class,response
0,"[\n {\n ""word"": ""leivatootmises"",\n ""co...",gpt-4,belongings,"[\n {\n ""word"": ""leivatootmises"",\n ""co..."
1,"[\n {\n ""word"": ""p\u00fcsit\u00f6\u00f6le""...",gpt-4,belongings,"[\n {\n ""word"": ""püsitööle"",\n ""output""..."
2,"[\n {\n ""word"": ""Raatusesse"",\n ""contex...",gpt-4,belongings,"[\n {\n ""word"": ""Raatusesse"",\n ""output..."
3,"[\n {\n ""word"": ""suusap\u00e4eval"",\n ""...",gpt-4,belongings,"[\n {\n ""word"": ""suusapäeval"",\n ""outpu..."
4,"[\n {\n ""word"": ""lastehommikule"",\n ""co...",gpt-4,belongings,"[\n {\n ""word"": ""lastehommikule"",\n ""ev..."
...,...,...,...,...
1395,"[\n {\n ""word"": ""parlamendilt"",\n ""cont...",gpt-4,platforms_and_floors,"[\n {\n ""word"": ""parlamendilt"",\n ""cont..."
1396,"[\n {\n ""word"": ""perele"",\n ""context"": ...",gpt-4,platforms_and_floors,"[\n {\n ""word"": ""perele"",\n ""context"": ..."
1397,"[\n {\n ""word"": ""olukorrale"",\n ""contex...",gpt-4,platforms_and_floors,"[\n {\n ""word"": ""olukorrale"",\n ""can_st..."
1398,"[\n {\n ""word"": ""maailmas"",\n ""context""...",gpt-4,platforms_and_floors,"[\n {\n ""word"": ""maailmas"",\n ""can_stan..."
1399,"[\n {\n ""word"": ""detsembril"",\n ""contex...",gpt-4,platforms_and_floors,"[\n {\n ""word"": ""detsembril"",\n ""can_st..."

In [3]:
print(df["response"][425])
df = df.drop(425)

[
  {
    "word": "ristil\u00f6\u00f6misele",
    "context": "Palmipuudep\u00fcha on kristlaste paastu viimane ehk kuues p\u00fchap\u00e4ev , sel p\u00e4eval sisenes Jeesus usutavasti p\u00fcha Jeruusalemma , vastu oma ristil\u00f6\u00f6misele .",
    "isPersonalName": "0"
  },
  {
    "word": "ristil\u00f6\u00f6misest",
    "context": "Eelmise jutukese kommentaarides ma kirjutasin natuke ristil\u00f6\u00f6misest : keda l\u00f6\u00f6di , kuidas l\u00f6\u00f6di ja miks maha ei v\u00f5etud .",
    "isPersonalName": "0"
  },
  {
    "word": "ristil\u00f6\u00f6misel",
    "context": "\" Paljud juudiorganisatsioonid ja isikud \u00fctlesid meile , et film tekitab etnilist vihkamist ning viljeleb ksenofoobseid m\u00fc\u00fcte juutide s\u00fc\u00fc kohta Kristuse ristil\u00f6\u00f6misel , \" \u00fctles Moskva inim\u00f5iguste b\u00fcroo direktor Aleksandr Brod neljap\u00e4eval Interfaksile .",
    "isPersonalName": "0"
  },
  {
    "word": "ristil\u00f6\u00f6misele",
    "context": "Kuid risti

In [4]:
print(df["response"][609])
df = df.drop(609)

[
  {
    "word": "härrasrahvas",
    "context": "Probleemi olemasolu paljastas meie kõige salajasema hirmu ( mis oli ilmselt pärit aastasadu kestnud alandamisest ) : mida härrasrahvas minu tegevusest arvab ?",
    "is_location": "0"
  },
  {
    "word": "härrasrahvas",
    "context": "\" Sageli käib õhtusel ajal väliterrassil istumas kontserdilt või teatrist tulnud härrasrahvas - smokingutes ja siidkleitides , \" kirjeldas Hakomaa õhtuseid kliente .",
    "is_location": "0"
  },
  {
    "word": "härrasrahvale",
    "context": "Võõrkeelsele härrasrahvale lisab sära Ameerika suursaadik Eestis emand Melissa Wells koos abikaasaga .",
    "is_location": "0"
  },
  {
    "word": "härrasrahvas",
    "context": "Mothander kirjeldab uhke mõisa omanike elu suvel - härrasrahvas käis ise peenraid rohimas ja aiasaadusi Tallinna turul müümas .",
    "is_location": "0"
  },
  {
    "word": "Härrasrahval",
    "context": "Härrasrahval ei sobi alaväärsetega koos kulgeda , nii võiks kõlada tigedavõitu

In [5]:
print(df["response"][809])
df = df.drop(809)

None

In [6]:
print(df["response"][1109])
df = df.drop(1109)

None

In [7]:
print(df["response"][1209])
df = df.drop(1209)

None

In [8]:
import pandas as pd
import re

# leiame 'response' veerust kõik sõnade ja väärtuste paarid
def extract_pairs(text):
    if not isinstance(text, str):
        return []
    
    word = re.findall(r'"word": "([^"]*)"', text) #leiab järgmisel kujul sõned ["word": "naftariigil"]
    märgendused = re.findall(r'"(?:\w|\s)+":\s*"?(0|1)"?(?!\d)', text) #leiab järgmisel kujul sõned ["evaluation": "0"]
    if len(märgendused) != 5 or len(word) < 1:
        print(text)
    else:
        value = 0
        for märgendus in märgendused:
            value += int(märgendus)
    word = word[0]   
    # parandame encoding vigu
    word = re.sub(r'(\Wu00e4)', 'ä', word)
    word = re.sub(r'(\Wu00f5)', 'õ', word)
    word = re.sub(r'(\Wu00fc)', 'ü', word)
    word = re.sub(r'(\Wu00f6)', 'ö', word)
    word = re.sub(r'(\Wu00dc)', 'Ü', word)
    
    return word, int(value)

In [9]:
# loome uue dataframe'i, kus on iga leitud sõna kohta rida
# igas reas on sõna, semantiline_klass ja ennustus

rows = []
i = 0
# Loop through each row in the original DataFrame
for _, row in df.iterrows():
    i+=1
    semantic_class = row['semantic_class']
    word_value_pairs = extract_pairs(row['response'])
    rows.append({
            'lemma': word_value_pairs[0],
            'väärtus': int(word_value_pairs[1]),
            'semantiline_klass': semantic_class
        })

simple_df = pd.DataFrame(rows)
simple_df

               lemma  väärtus     semantiline_klass
0     leivatootmises        0            belongings
1          püsitööle        0            belongings
2         Raatusesse        0            belongings
3        suusapäeval        0            belongings
4     lastehommikule        0            belongings
...              ...      ...                   ...
1390    parlamendilt        2  platforms_and_floors
1391          perele        0  platforms_and_floors
1392      olukorrale        0  platforms_and_floors
1393        maailmas        0  platforms_and_floors
1394      detsembril        0  platforms_and_floors

[1395 rows x 3 columns]

In [10]:
# Saame loodud dataframe'ist lõpliku tulemuse, kus on semantilised_klassid veergude nimed
final_df = simple_df.pivot_table(index='lemma', 
                            columns='semantiline_klass', 
                            values='väärtus', 
                            aggfunc='first') 




final_df.columns.name = None 
final_df = final_df.reset_index()
final_df

,lemma,belongings,clothing_items,edibles,enclosures_and_vehicles,geographical_locations,institutions,nonsense_words,organisations_and_events,persons,platforms_and_floors,spatial_directions,spatial_region,time_expressions,vegetative_enclosure
0,Acapulcos,0.0,0.0,0.0,5.0,5.0,4.0,5.0,5.0,0.0,0.0,5.0,5.0,0.0,0.0
1,Bolognas,0.0,0.0,0.0,5.0,5.0,0.0,5.0,1.0,0.0,2.0,5.0,5.0,1.0,0.0
2,Darwinilt,0.0,1.0,0.0,3.0,3.0,0.0,5.0,0.0,2.0,3.0,4.0,3.0,0.0,0.0
3,Hebronist,0.0,0.0,0.0,5.0,5.0,0.0,5.0,0.0,0.0,5.0,5.0,5.0,0.0,0.0
4,Häädemeestel,0.0,0.0,0.0,5.0,5.0,1.0,5.0,1.0,0.0,1.0,5.0,5.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,veefestivalil,0.0,0.0,0.0,5.0,1.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0,2.0,0.0
97,vändras,0.0,0.0,0.0,5.0,5.0,0.0,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0
98,win-s,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,õhtuses,0.0,3.0,0.0,0.0,0.0,2.0,2.0,1.0,2.0,2.0,0.0,0.0,4.0,0.0
100,ümbrisel,5.0,1.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
pd.set_option('display.max_rows', None)

# Print all values in the column
print(final_df["lemma"])

0                Acapulcos
1                 Bolognas
2                Darwinilt
3                Hebronist
4             Häädemeestel
5                     Just
6                 Kozlovil
7                   Leidal
8                 Lembitul
9                    MTÜ-s
10                  Macaus
11                 Mexicos
12                  RAM-is
13              Raatusesse
14               Rate.ee-s
15                  Saksas
16                Sopotist
17            VANA-KREEKAS
18            Võrkpalluril
19             Williamsile
20          alkoholiravilt
21     banaanivabariikides
22              detsembril
23           dikteerimisel
24               erikoolis
25           eskalaatorist
26              habemikult
27            härrasrahvas
28                imaveres
29                isakodus
30          joobeseisundis
31            juveelipoest
32                 kahinas
33           kallaletungis
34            kanuumatkale
35           keemialaboris
36           kindlustatult
37          kodustaadionil
38              kontekstis
39           kontoriruumis
40          kontrollmängus
41           korraldamises
42             kuluaarides
43            kuuldemängus
44        lahingutegevuses
45           laristamisest
46          lastehommikule
47          leivatootmises
48            lennusadamas
49           linnamisjonis
50             linnarahval
51        linnavaraametile
52            lootusetuses
53          luurekeskusele
54                  lössis
55                maailmas
56             mardipäeval
57           messikeskuses
58        metsasügavustest
59             moenädalalt
60            munakividest
61            mänguminutil
62             naftariigil
63              olukorrale
64                   ootel
65              ooteruumis
66            osoonikihist
67            parlamendilt
68             patareidest
69                  perele
70             pingutusele
71         presidendiajast
72            pronksikohal
73             põhivormile
74            pöördtoolilt
75               püsitööle
76          rahvuslikkuses
77         rambivalgusesse
78            revüteatrile
79           revüüteatrile
80          ristilöömisele
81                sisemaal
82                skeemile
83             suusapäeval
84              sõidurajal
85             süüdistuses
86            taastamisele
87             taktimõõdus
88            taliolümpial
89             talvepäeval
90           tootmishoones
91                 turneel
92              turvamisel
93               töökätest
94                töölaual
95                vahepial
96           veefestivalil
97                 vändras
98                   win-s
99                 õhtuses
100               ümbrisel
Name: lemma, dtype: object

In [12]:
# salvestame loodud dataframe'i
final_df.to_csv('GPT4_tulemused_kontekstiga.csv', index=False)